{% set name = "zwatershed" %}
{% set version = "0.10" %}
{% set checksum = "4892f63d5aefb7dd5ae199c4481e94c88ce7e398d30cd90fa45fa555587ff5c1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  skip: true  # [win or py3k]
  number: 1001
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - boost
    - python
    - setuptools >=18.0
    - numpy
    - cython >=0.23
    - h5py

  run:
    - boost
    - python
    - {{ pin_compatible('numpy') }}
    - h5py

test:
  imports:
    - zwatershed

about:
  home: https://github.com/TuragaLab/zwatershed
  license: MIT
  summary: 'Code for fast watersheds.'

extra:
  recipe-maintainers:
    - csinva
