travis:
  secure:
    BINSTAR_TOKEN: wpxulvVXDiU+Bt9Sf1fleocNTUvDZC9FFPODuHDHJuPyK+LtZH+ECDCSPJqqo5jQC5QHnMhE0YctM2hkD9CWlzz9ANfcMFMoam+Dmc0amy+q7nNlYOI2w4g6vh6Ls2aKyFpuobnnnnB+nFdYh8AvVKyQwWBEBUrEWOxUOMIb2MXzN8leTBnbvZ0hPdZog5Dy7gl54+gqFLuNgGGhNMtnzUZg8HPt2Quez5Y+Va2GrcU+ItizuA1o1Ak4oo6MJ0W1lVPmorUxOTHP5+DgKPVpfY7fpRPZ4E49Wo/qbO0Bvn50HeCpGp5+wZGna7KwZ0gEaMg1N34hB91pAjqlzx9WiRGcCMT1M6QnfDHkbxcxQsB4MGNOFTH6dKy9UTmVky/Ifw0HkZwVzB4OU4ieRG5MaYcNHXPXa5wjvvt2zy1cLUCZ5Bq3i+xhs8hN4S9fQbc7Py7M77uz60ytMTdvkEHmoIdKRU+hAMeO0wJMiB0zuchXiOguZZzVyWuXB/ILOm/ZyqwzIiQFQ39y8l9DeTuEZh5uTIjz3Q/GYu2aiROvXtgUyjRH6XoHmbJhB6HKMkSVbPl58+kRgAq9grHMp0Kn1bagVHKP3Y8bd8EysLQtMqtRFhedWCpobJAM/a8MYCxGL7c7eHhfnt2Asr+gHw76KeNWGZfOE0WixGbp8kOZHUs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
